version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ani123
      POSTGRES_USER: ani
      POSTGRES_DB: db123
    app:
      image: my-node-app
      port: 
        - 13000:3000n